spring.application.name=account-service
server.port=8011
spring.datasource.url=jdbc:postgresql://localhost:5433/account_service
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.profiles.active=dev